import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { APP_URL, APP_NAME, APP_DESCRIPTION } from "~/lib/constants";
import { getMiniAppEmbedMetadata } from "~/lib/utils";

export const revalidate = 300;

// This is an example of how to generate a dynamically generated share page based on fid:
// Sharing this route e.g. example.com/share/123?mode=weekly will generate a share page for fid 123,
// with the image dynamically generated by the /api/thumbnail API route.
export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ fid: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}): Promise<Metadata> {
  const resolvedParams = await params;
  const resolvedSearch = await searchParams;

  const { fid } = resolvedParams;
  const imageUrl = new URL(`${APP_URL}/api/thumbnail`);
  imageUrl.searchParams.set("fid", fid);

  // Pass through selected query parameters to hydrate the thumbnail
  const passthroughKeys = ["mode", "score", "time", "questions", "accuracy"];
  for (const key of passthroughKeys) {
    const value = resolvedSearch?.[key];
    if (!value) continue;

    if (Array.isArray(value)) {
      // Use the first occurrence for deterministic behavior
      imageUrl.searchParams.set(key, value[0]);
    } else {
      imageUrl.searchParams.set(key, value);
    }
  }

  const finalImageUrl = imageUrl.toString();

  return {
    title: `${APP_NAME} - Share`,
    openGraph: {
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [finalImageUrl],
    },
    other: {
      "fc:frame": JSON.stringify(getMiniAppEmbedMetadata(finalImageUrl)),
      "fc:miniapp": JSON.stringify(getMiniAppEmbedMetadata(finalImageUrl)),
    },
  };
}

export default function SharePage() {
  // redirect to home page
  redirect("/");
}
